[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "jsbeautifier>=1.15.4",
    "openai>=1.97.1",
    "tqdm>=4.67.1",
]
